# Generated by Django 5.2.6 on 2025-10-11 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_alter_productsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize'),
        ),
    ]
