# Generated by Django 5.2.6 on 2025-10-08 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice_is_deleted'),
        ('products', '0002_product_out_of_stock_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsize'),
        ),
    ]
